ARG IMAGE_VERSION=latest
FROM ubuntu:$IMAGE_VERSION
LABEL org.opencontainers.image.description="" \
      org.opencontainers.image.authors="Nikolay Kostov (https://www.linkedin.com/in/nikolay-kostov-689364131/)" \
      org.opencontainers.image.url="ghcr.io/nickkostov/dockerfiles/ubuntu:latest" \
      org.opencontainers.image.documentation="https://github.com/nickkostov/dockerfiles/os/ubuntu/README.md" \
      org.opencontainers.image.source="https://github.com/nickkostov/dockerfiles/os/ubuntu"

# Add any specific configurations or packages here
